CREATE USER IF NOT EXISTS 'dennis'@'%' IDENTIFIED BY 'dennis';
GRANT ALL PRIVILEGES ON login_demo.* TO 'dennis'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS session (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255)
);
